### ISSUE TITLE
Example of how to use custom templates?

### ISSUE THREAD

**Issue by Ziriax** [asciidoctor/asciidoctor-cli.js#115]
I have no luck getting custom templates working with @asciidoctor/cli

I tried various combinations, but nothing works, and I get very little feedback from the tool.

For example, running  (on Windows)

`node_modules\.bin\asciidoctor --trace -v --template-dir src/templates --template-engine blablabla src/guide.adoc`  

doesn't output an error because template engine `blablabla` doesn't exist. 

Could someone give an example of how to override the built-in templates?

In my case I want to insert `preload=lazy` for each `img` tag.

Thanks a lot!
Peter

PS: For the Ruby version, that uses ERB templates, this was explained [here](https://stackoverflow.com/questions/63917971/how-to-create-custom-html-output-for-an-existing-asciidoctor-asciidoc-macro)

**Comment by Mogztter** [comment]
Hello @Ziriax 

Your command is correct, even though the option `--template-engine` is ignored/not used in Asciidoctor.js.
Which template engine are you using?

By default, Asciidoctor.js supports EJS (`.ejs`), Handlebars(`.handlebars`, `.hbs`), Nunjucks (`.nunjucks`, `.njk`), Pug (`.pug`) and Template Literals.

You can learn more about the template converter here: https://asciidoctor-docs.netlify.app/asciidoctor.js/extend/converter/template-converter/

The implementation is slightly different from Asciidoctor (Ruby) because JavaScript and Ruby have different templating engines. Asciidoctor (Ruby) is also using [Tilt](https://github.com/rtomayko/tilt) -- a thin interface over a bunch of different Ruby template engines -- but in JavaScript no such library exists.

> In my case I want to insert preload=lazy for each img tag.

Asciidoctor is using `image` for block image (ie. `image::` with 2 colons) and `inline_image` for inline image (ie. `image:` with one colon). Let's say that you want to use Nunjucks then you will need to create two files in `src/templates`:

- `src/templates/image.njk`
- `src/templates/inline_image.njk`

You will also need to install the dependency on Nunjucks: `npm i nunjucks --save` otherwise you will get the following error:

```
IOError: Unable to require the module 'nunjucks', please make sure that the module is installed
```

> PS: For the Ruby version, that uses ERB templates, this was explained here

Since Asciidoctor.js does not support ERB templates out-of-the-box, you will need to translate the syntax.
I recommend reading the API documentation of Asciidoctor.js to find out which functions are available on a specific `Node`: http://asciidoctor.github.io/asciidoctor.js/master/

**Comment by Ziriax** [comment]
Thanks for the detailed reply! 

> `src/templates/image.njk`

Ah, that might explain it, I was using `src/templates/block_image.njk` for testing 😄 

I will try again.

PS: I got it working with the Ruby version of asciidoctor, using the very nice docker image. As I only need lazy loading for building the production HTML, this works for me. I'm only using asciidoctor.js indirectly through the vscode plugin.

**Comment by Mogztter** [comment]
The suffix `block_` is deprecated but it should still work.

> PS: I got it working with the Ruby version of asciidoctor, using the very nice docker image. As I only need lazy loading for building the production HTML, this works for me. I'm only using asciidoctor.js indirectly through the vscode plugin.

:+1: 

I will keep this issue open as a reminder to update the documentation of the CLI to explain how to use templates.

**Comment by Mogztter** [comment]
The documentation is live: https://asciidoctor-docs.netlify.app/asciidoctor.js/cli/options/#document-conversion (temporary URL)
